import React, { useState, useEffect } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Chip,
  IconButton,
  Alert,
  CircularProgress,
  Box,
  Typography,
  TextField,
  InputAdornment,
  MenuItem,
} from '@mui/material';
import {
  Add as AddIcon,
  CheckCircle as ActivarIcon,
  Block as DesactivarIcon,
  Delete as DeleteIcon,
} from '@mui/icons-material';
import Autocomplete from '@mui/material/Autocomplete';
import { proveedorProductoApi } from '../../api/services/proveedorProductoApi';
import { productApi } from '../../api/services/productApi';
import { categoriaProductoApi } from '../../api/services/categoriaProductoApi';
import type { ProveedorDTO, ProveedorProductoDTO, Producto, CategoriaProducto } from '../../types';

interface Props {
  open: boolean;
  proveedor: ProveedorDTO | null;
  onClose: () => void;
}

const ProveedorProductosDialog: React.FC<Props> = ({ open, proveedor, onClose }) => {
  const [relaciones, setRelaciones] = useState<ProveedorProductoDTO[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [todosProductos, setTodosProductos] = useState<Producto[]>([]);
  const [categorias, setCategorias] = useState<CategoriaProducto[]>([]);

  // Sub-dialog "Asociar producto"
  const [openAsociar, setOpenAsociar] = useState(false);
  const [productoSeleccionado, setProductoSeleccionado] = useState<Producto | null>(null);
  const [inputValue, setInputValue] = useState('');
  const [precioInput, setPrecioInput] = useState('');
  const [savingAsociar, setSavingAsociar] = useState(false);
  const [errorAsociar, setErrorAsociar] = useState<string | null>(null);

  // New-product fields
  const [esProductoNuevo, setEsProductoNuevo] = useState(false);
  const [nombreNuevo, setNombreNuevo] = useState('');
  const [categoriaId, setCategoriaId] = useState('');
  const [codigoGenerado, setCodigoGenerado] = useState('');

  // Confirm eliminar
  const [confirmEliminarId, setConfirmEliminarId] = useState<number | null>(null);

  useEffect(() => {
    if (open && proveedor) {
      loadRelaciones();
      loadTodosProductos();
      loadCategorias();
    }
  }, [open, proveedor]);

  const loadRelaciones = async () => {
    if (!proveedor) return;
    try {
      setLoading(true);
      setError(null);
      const data = await proveedorProductoApi.getByProveedor(proveedor.id);
      setRelaciones(data);
    } catch (err: any) {
      setError('Error al cargar los productos del proveedor');
    } finally {
      setLoading(false);
    }
  };

  const loadTodosProductos = async () => {
    try {
      const page = await productApi.getAll({ size: 10000 });
      const data = Array.isArray(page) ? page : (page?.content ?? []);
      setTodosProductos(data);
    } catch {
      // silencioso
    }
  };

  const loadCategorias = async () => {
    try {
      const data = await categoriaProductoApi.getAll();
      setCategorias(data);
    } catch {
      // silencioso
    }
  };

  // Generate code like ComprasPedidosPage: first 3 letters of category + sequential number
  const generateProductCode = (catId: string): string => {
    if (!catId) return '';
    const categoria = categorias.find((c) => c.id.toString() === catId);
    if (!categoria) return '';
    const prefix = categoria.nombre.substring(0, 3).toUpperCase();
    const existingCodes = todosProductos
      .filter((p) => p.codigo && p.codigo.startsWith(prefix))
      .map((p) => p.codigo!);
    let maxNumber = 0;
    existingCodes.forEach((code) => {
      const num = parseInt(code.replace(prefix, ''), 10);
      if (!isNaN(num) && num > maxNumber) maxNumber = num;
    });
    return `${prefix}${(maxNumber + 1).toString().padStart(3, '0')}`;
  };

  const handleCategoriaChange = (value: string) => {
    setCategoriaId(value);
    const isAutoGenerated = /^[A-Z]{3}\d{3}$/.test(codigoGenerado);
    if (!codigoGenerado || isAutoGenerated) {
      setCodigoGenerado(generateProductCode(value));
    }
  };

  const handleActivar = async (id: number) => {
    try {
      const updated = await proveedorProductoApi.activar(id);
      setRelaciones((prev) => prev.map((r) => (r.id === id ? updated : r)));
    } catch (err: any) {
      setError(err.response?.data?.message || 'Error al activar el producto');
    }
  };

  const handleDesactivar = async (id: number) => {
    try {
      const updated = await proveedorProductoApi.desactivar(id);
      setRelaciones((prev) => prev.map((r) => (r.id === id ? updated : r)));
    } catch (err: any) {
      setError(err.response?.data?.message || 'Error al desactivar el producto');
    }
  };

  const handleEliminar = async (id: number) => {
    try {
      await proveedorProductoApi.delete(id);
      setRelaciones((prev) => prev.filter((r) => r.id !== id));
      setConfirmEliminarId(null);
    } catch (err: any) {
      setError(err.response?.data?.message || 'Error al eliminar el producto');
      setConfirmEliminarId(null);
    }
  };

  const handleGuardarAsociar = async () => {
    if (!proveedor) return;
    try {
      setSavingAsociar(true);
      setErrorAsociar(null);

      let productoId: number;

      if (esProductoNuevo) {
        if (!nombreNuevo.trim()) {
          setErrorAsociar('El nombre del producto es requerido');
          return;
        }
        if (!categoriaId) {
          setErrorAsociar('La categoría es requerida para crear un nuevo producto');
          return;
        }
        const nuevoProducto = await productApi.create({
          nombre: nombreNuevo.trim(),
          descripcion: nombreNuevo.trim(),
          precio: precioInput ? parseFloat(precioInput) : 0,
          costo: null,
          stockActual: 0,
          stockMinimo: 0,
          codigo: codigoGenerado || undefined,
          categoriaProductoId: parseInt(categoriaId),
        });
        productoId = nuevoProducto.id;
        // Refresh product list so codes stay in sync
        loadTodosProductos();
      } else {
        if (!productoSeleccionado) return;
        productoId = productoSeleccionado.id;
      }

      const nuevaRelacion = await proveedorProductoApi.create({
        proveedorId: proveedor.id,
        productoId,
        precioProveedor: precioInput ? parseFloat(precioInput) : undefined,
      });
      setRelaciones((prev) => [...prev, nuevaRelacion]);
      handleCloseAsociar();
    } catch (err: any) {
      setErrorAsociar(
        err.response?.data?.message || 'Error al asociar el producto'
      );
    } finally {
      setSavingAsociar(false);
    }
  };

  const handleCloseAsociar = () => {
    setOpenAsociar(false);
    setProductoSeleccionado(null);
    setInputValue('');
    setPrecioInput('');
    setErrorAsociar(null);
    setEsProductoNuevo(false);
    setNombreNuevo('');
    setCategoriaId('');
    setCodigoGenerado('');
  };

  const productosDisponibles = todosProductos.filter(
    (p) => !relaciones.some((r) => r.productoId === p.id)
  );

  const canGuardar = esProductoNuevo
    ? !!nombreNuevo.trim() && !!categoriaId
    : !!productoSeleccionado;

  return (
    <>
      <Dialog open={open} onClose={onClose} maxWidth="md" fullWidth>
        <DialogTitle>
          <Box display="flex" justifyContent="space-between" alignItems="center">
            <Typography variant="h6">
              Productos — {proveedor?.razonSocial}
            </Typography>
            <Button
              variant="contained"
              startIcon={<AddIcon />}
              onClick={() => setOpenAsociar(true)}
              size="small"
            >
              Asociar producto
            </Button>
          </Box>
        </DialogTitle>

        <DialogContent>
          {error && (
            <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError(null)}>
              {error}
            </Alert>
          )}

          {loading ? (
            <Box display="flex" justifyContent="center" py={4}>
              <CircularProgress />
            </Box>
          ) : (
            <TableContainer component={Paper} variant="outlined">
              <Table size="small">
                <TableHead>
                  <TableRow>
                    <TableCell>Código</TableCell>
                    <TableCell>Nombre</TableCell>
                    <TableCell>Precio proveedor</TableCell>
                    <TableCell>Estado</TableCell>
                    <TableCell align="center">Acciones</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {relaciones.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={5} align="center">
                        <Typography variant="body2" color="text.secondary" py={2}>
                          No hay productos asociados a este proveedor
                        </Typography>
                      </TableCell>
                    </TableRow>
                  ) : (
                    relaciones.map((rel) => (
                      <TableRow key={rel.id}>
                        <TableCell>{rel.productoCodigo}</TableCell>
                        <TableCell>{rel.productoNombre}</TableCell>
                        <TableCell>
                          {rel.precioProveedor != null
                            ? `$${rel.precioProveedor.toFixed(2)}`
                            : '-'}
                        </TableCell>
                        <TableCell>
                          <Chip
                            size="small"
                            label={rel.activo ? 'Activo' : 'Inactivo'}
                            color={rel.activo ? 'success' : 'default'}
                          />
                        </TableCell>
                        <TableCell align="center">
                          {rel.activo ? (
                            <IconButton
                              size="small"
                              title="Desactivar"
                              onClick={() => handleDesactivar(rel.id)}
                            >
                              <DesactivarIcon fontSize="small" />
                            </IconButton>
                          ) : (
                            <IconButton
                              size="small"
                              title="Activar"
                              onClick={() => handleActivar(rel.id)}
                            >
                              <ActivarIcon fontSize="small" />
                            </IconButton>
                          )}
                          <IconButton
                            size="small"
                            title="Eliminar"
                            color="error"
                            disabled={rel.activo}
                            onClick={() => setConfirmEliminarId(rel.id)}
                          >
                            <DeleteIcon fontSize="small" />
                          </IconButton>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        </DialogContent>

        <DialogActions>
          <Button onClick={onClose}>Cerrar</Button>
        </DialogActions>
      </Dialog>

      {/* Sub-dialog: Asociar producto */}
      <Dialog open={openAsociar} onClose={handleCloseAsociar} maxWidth="sm" fullWidth>
        <DialogTitle>Asociar producto a {proveedor?.razonSocial}</DialogTitle>
        <DialogContent>
          <Box display="flex" flexDirection="column" gap={2} mt={1}>
            {errorAsociar && (
              <Alert severity="error">{errorAsociar}</Alert>
            )}

            <Autocomplete
              freeSolo
              options={productosDisponibles}
              getOptionLabel={(option) =>
                typeof option === 'string'
                  ? option
                  : `${option.nombre} (${option.codigo || 'sin código'})`
              }
              isOptionEqualToValue={(option, value) =>
                typeof option === 'object' && typeof value === 'object' && option.id === value.id
              }
              value={productoSeleccionado}
              inputValue={inputValue}
              onChange={(_, newValue) => {
                if (typeof newValue === 'string') {
                  setProductoSeleccionado(null);
                  setNombreNuevo(newValue);
                  setEsProductoNuevo(true);
                } else if (newValue && typeof newValue === 'object') {
                  setProductoSeleccionado(newValue);
                  setInputValue(newValue.nombre);
                  setEsProductoNuevo(false);
                  setNombreNuevo('');
                  setCategoriaId('');
                  setCodigoGenerado('');
                } else {
                  setProductoSeleccionado(null);
                  setEsProductoNuevo(false);
                  setNombreNuevo('');
                  setCategoriaId('');
                  setCodigoGenerado('');
                }
              }}
              onInputChange={(_, newInputValue, reason) => {
                setInputValue(newInputValue);
                if (reason === 'input') {
                  if (!productoSeleccionado) {
                    const isNew = newInputValue.trim() !== '';
                    setEsProductoNuevo(isNew);
                    setNombreNuevo(newInputValue);
                    if (!isNew) {
                      setCategoriaId('');
                      setCodigoGenerado('');
                    }
                  }
                } else if (reason === 'clear') {
                  setProductoSeleccionado(null);
                  setEsProductoNuevo(false);
                  setNombreNuevo('');
                  setCategoriaId('');
                  setCodigoGenerado('');
                }
              }}
              renderInput={(params) => (
                <TextField
                  {...params}
                  label="Producto"
                  required
                  placeholder="Buscar existente o escribir nuevo..."
                  helperText={
                    esProductoNuevo
                      ? 'Nuevo producto — se creará al guardar'
                      : productoSeleccionado
                      ? 'Producto existente seleccionado'
                      : ''
                  }
                />
              )}
            />

            {esProductoNuevo && (
              <Box display="flex" gap={2} flexWrap="wrap">
                <TextField
                  select
                  label="Categoría *"
                  value={categoriaId}
                  onChange={(e) => handleCategoriaChange(e.target.value)}
                  sx={{ minWidth: 200 }}
                  required
                  error={!categoriaId}
                  helperText="Requerido — genera código automáticamente"
                >
                  <MenuItem value="">Seleccione...</MenuItem>
                  {categorias.map((cat) => (
                    <MenuItem key={cat.id} value={cat.id.toString()}>
                      {cat.nombre}
                    </MenuItem>
                  ))}
                </TextField>
                <TextField
                  label="Código"
                  value={codigoGenerado}
                  onChange={(e) => setCodigoGenerado(e.target.value)}
                  sx={{ minWidth: 150 }}
                  helperText="Auto-generado (editable)"
                />
              </Box>
            )}

            <TextField
              label="Precio del proveedor (opcional)"
              type="number"
              value={precioInput}
              onChange={(e) => setPrecioInput(e.target.value)}
              InputProps={{
                startAdornment: <InputAdornment position="start">$</InputAdornment>,
              }}
              inputProps={{ min: 0, step: '0.01' }}
            />
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCloseAsociar} disabled={savingAsociar}>
            Cancelar
          </Button>
          <Button
            variant="contained"
            onClick={handleGuardarAsociar}
            disabled={!canGuardar || savingAsociar}
          >
            {savingAsociar ? 'Guardando...' : 'Guardar'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Confirm eliminar */}
      <Dialog open={confirmEliminarId !== null} onClose={() => setConfirmEliminarId(null)}>
        <DialogTitle>Confirmar eliminación</DialogTitle>
        <DialogContent>
          <Typography>
            ¿Eliminar este producto de la lista del proveedor? Esta acción no se puede deshacer.
          </Typography>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setConfirmEliminarId(null)}>Cancelar</Button>
          <Button
            variant="contained"
            color="error"
            onClick={() => confirmEliminarId !== null && handleEliminar(confirmEliminarId)}
          >
            Eliminar
          </Button>
        </DialogActions>
      </Dialog>
    </>
  );
};

export default ProveedorProductosDialog;
